const express=require('express');const crypto=require('node:crypto');const{z}=require('zod');const pool=require('../db');const{requireRole}=require('../middleware/auth');const{inputSchema,primitives}=require('../services/tools');const{audit,rateLimit}=require('../lib/security');
const router=express.Router();
const caseSchema=z.object({name:z.string().min(1).max(160),input:inputSchema,expectedPrimitives:z.array(z.enum(primitives)).min(1).max(20),minGroundedScore:z.number().min(0).max(1).default(1)});
const gatesSchema=z.object({minPassRate:z.number().min(0).max(1).default(.9),minGroundedScore:z.number().min(0).max(1).default(1),minSafetyPassRate:z.number().min(0).max(1).default(1),maxAverageLatencyMs:z.number().int().min(1000).max(60000).default(15000),maxTotalCostUsd:z.number().positive().max(100).default(5),caseTimeoutMs:z.number().int().min(1000).max(60000).default(20000),caseCostBudgetUsd:z.number().positive().max(10).default(.5),maxCaseLatencyMs:z.number().int().min(1000).max(60000).default(20000)});
router.get('/',requireRole('reviewer','tenant_admin'),async(req,res,next)=>{try{const[cases,runs]=await Promise.all([pool.query(`SELECT * FROM evaluation_cases WHERE tenant_id=$1 ORDER BY name`,[req.user.tenant_id]),pool.query(`SELECT * FROM evaluation_runs WHERE tenant_id=$1 ORDER BY created_at DESC LIMIT 100`,[req.user.tenant_id])]);res.json({cases:cases.rows,runs:runs.rows});}catch(error){next(error);}});
router.post('/cases',requireRole('tenant_admin'),async(req,res,next)=>{try{const body=caseSchema.parse(req.body);const id=crypto.randomUUID();const result=await pool.query(`INSERT INTO evaluation_cases(id,tenant_id,name,tool,input,expected_primitives,min_grounded_score) VALUES($1,$2,$3,'grounded_interface_proposal',$4,$5,$6) RETURNING *`,[id,req.user.tenant_id,body.name,body.input,body.expectedPrimitives,body.minGroundedScore]);res.status(201).json({case:result.rows[0]});}catch(error){next(error);}});
router.post('/runs',requireRole('reviewer','tenant_admin'),async(req,res,next)=>{try{await rateLimit(req.user,'evaluation-run',10,3600);const gates=gatesSchema.parse(req.body?.gates||{});const id=crypto.randomUUID();const client=await pool.connect();try{await client.query('BEGIN');const result=await client.query(`INSERT INTO evaluation_runs(id,tenant_id,created_by,gates) VALUES($1,$2,$3,$4) RETURNING *`,[id,req.user.tenant_id,req.user.id,gates]);await audit(client,{tenantId:req.user.tenant_id,actorId:req.user.id,action:'evaluation.queued',targetType:'evaluation_run',targetId:id,input:gates});await client.query('COMMIT');res.status(202).json({run:result.rows[0]});}catch(error){await client.query('ROLLBACK');throw error;}finally{client.release();}}catch(error){next(error);}});
router.get('/runs/:id',requireRole('reviewer','tenant_admin'),async(req,res,next)=>{try{const run=await pool.query(`SELECT * FROM evaluation_runs WHERE id=$1 AND tenant_id=$2`,[req.params.id,req.user.tenant_id]);if(!run.rows[0])return res.status(404).json({error:'Run not found'});const results=await pool.query(`SELECT r.*,c.name FROM evaluation_results r JOIN evaluation_cases c ON c.id=r.case_id WHERE r.run_id=$1 AND r.tenant_id=$2 ORDER BY c.name`,[req.params.id,req.user.tenant_id]);res.json({run:run.rows[0],results:results.rows});}catch(error){next(error);}});
module.exports=router;
