INSERT INTO users (email, password_hash, name, role) VALUES
('admin@demo.com', '$2b$10$e4dPQpe3XIDluCZCv3b3iu/H/3f816tgim6l5ly5k7pChHG235Dey', 'Admin User', 'admin')
ON CONFLICT DO NOTHING;

INSERT INTO ui_users (name, email, role, persona, interface_layout, theme, density, active_since, session_count, satisfaction_score) VALUES
('Alex Chen', 'alex.chen@company.com', 'Senior Engineer', 'power_user', 'dashboard', 'dark', 'compact', '2023-01-15', 342, 4.6),
('Maria Santos', 'maria.santos@company.com', 'Product Manager', 'executive', 'kanban', 'light', 'comfortable', '2023-03-20', 178, 4.2),
('Jake Williams', 'jake.w@startup.com', 'Student Intern', 'student', 'calendar', 'light', 'spacious', '2024-06-01', 45, 3.8),
('Priya Patel', 'priya.patel@design.co', 'UX Designer', 'designer', 'grid', 'dark', 'compact', '2023-09-10', 267, 4.7),
('Tom Fischer', 'tom.fischer@corp.com', 'Engineering Manager', 'manager', 'timeline', 'dark', 'comfortable', '2022-11-05', 512, 4.4),
('Sarah Kim', 'sarah.kim@tech.io', 'Full Stack Developer', 'developer', 'tasklist', 'dark', 'compact', '2023-05-14', 398, 4.5),
('David Lee', 'david.lee@finance.com', 'CFO', 'executive', 'dashboard', 'light', 'comfortable', '2022-08-30', 156, 4.1),
('Anika Müller', 'anika.muller@design.eu', 'UI Designer', 'designer', 'grid', 'dark', 'spacious', '2023-07-22', 201, 4.8),
('Carlos Rivera', 'carlos.r@startup.io', 'Founder', 'executive', 'dashboard', 'dark', 'compact', '2022-05-01', 634, 4.3),
('Emma Johnson', 'emma.j@university.edu', 'Graduate Student', 'student', 'calendar', 'light', 'spacious', '2024-01-15', 87, 4.0),
('Michael Park', 'm.park@enterprise.com', 'Solutions Architect', 'developer', 'timeline', 'dark', 'compact', '2023-02-08', 289, 4.6),
('Lisa Thompson', 'lisa.t@agency.com', 'Project Manager', 'manager', 'kanban', 'light', 'comfortable', '2023-04-17', 445, 4.2),
('Ryan O''Brien', 'ryan.o@saas.com', 'Sales Engineer', 'power_user', 'dashboard', 'dark', 'compact', '2022-12-01', 378, 4.4),
('Zara Ahmed', 'zara.a@consulting.com', 'Business Analyst', 'manager', 'grid', 'light', 'comfortable', '2023-08-25', 134, 3.9),
('Oliver Nguyen', 'oliver.n@fintech.com', 'Backend Developer', 'developer', 'tasklist', 'dark', 'compact', '2023-11-12', 223, 4.5)
ON CONFLICT DO NOTHING;

INSERT INTO templates (name, description, layout, target_persona, primary_color, density, widgets_json, usage_count, rating) VALUES
('Power User Dashboard', 'Dense, information-rich layout with quick keyboard navigation', 'dashboard', 'power_user', '#6366f1', 'compact', '["metrics","recent-activity","quick-actions","notifications"]', 1247, 4.7),
('Executive Overview', 'Clean, high-level KPI view with minimal detail', 'dashboard', 'executive', '#0ea5e9', 'comfortable', '["kpi-summary","trend-chart","alerts","team-status"]', 892, 4.5),
('Developer Tasklist', 'Code-centric task management with PR and issue tracking', 'tasklist', 'developer', '#22c55e', 'compact', '["todo","pull-requests","builds","deployments"]', 2034, 4.8),
('Student Calendar View', 'Event-focused calendar with assignment tracking', 'calendar', 'student', '#f59e0b', 'spacious', '["monthly-calendar","upcoming-events","assignments","study-timer"]', 456, 4.3),
('Designer Canvas Grid', 'Visual grid layout with asset management and project tracking', 'grid', 'designer', '#ec4899', 'spacious', '["asset-grid","project-gallery","color-palette","inspiration-feed"]', 678, 4.6),
('Manager Kanban', 'Team workload visualization with sprint planning', 'kanban', 'manager', '#8b5cf6', 'comfortable', '["sprint-board","team-capacity","blockers","retrospective"]', 934, 4.4),
('Timeline Project View', 'Gantt-style timeline for project managers', 'timeline', 'manager', '#10b981', 'comfortable', '["gantt-chart","milestones","dependencies","resource-map"]', 567, 4.2),
('Minimal Focus Mode', 'Distraction-free single-task interface', 'tasklist', 'student', '#94a3b8', 'spacious', '["current-task","timer","notes","progress"]', 345, 4.1),
('Analytics Dashboard Pro', 'Data visualization heavy dashboard for analysts', 'dashboard', 'power_user', '#f97316', 'compact', '["charts","data-table","filters","export"]', 1123, 4.6),
('Mobile-First Grid', 'Responsive grid optimized for tablet and mobile', 'grid', 'student', '#06b6d4', 'comfortable', '["quick-access","recent","notifications","search"]', 234, 3.9),
('Collaboration Hub', 'Team communication and coordination central view', 'kanban', 'manager', '#6366f1', 'comfortable', '["team-feed","shared-docs","meetings","decisions"]', 789, 4.3),
('DevOps Pipeline View', 'CI/CD pipeline monitoring and deployment tracking', 'timeline', 'developer', '#14b8a6', 'compact', '["pipeline-status","deployments","monitoring","alerts"]', 412, 4.5),
('Design System Browser', 'Component library and design token management', 'grid', 'designer', '#8b5cf6', 'comfortable', '["components","tokens","documentation","version-history"]', 298, 4.4),
('Executive Briefing', 'Morning briefing with AI-summarized daily digest', 'dashboard', 'executive', '#1e40af', 'comfortable', '["daily-digest","critical-metrics","calendar","ai-insights"]', 567, 4.7),
('Compact Code Review', 'Ultra-dense code review focused developer view', 'tasklist', 'developer', '#dc2626', 'compact', '["open-prs","code-changes","comments","test-results"]', 876, 4.6)
ON CONFLICT DO NOTHING;

INSERT INTO widgets (name, type, description, data_source, config_schema, category, popularity) VALUES
('Revenue Chart', 'chart', 'Real-time revenue trend visualization with forecasting', 'billing-api', '{"timeRange":"30d","currency":"USD","forecast":true}', 'analytics', 892),
('Task Board', 'kanban', 'Drag-and-drop kanban board for task management', 'tasks-api', '{"columns":["todo","in-progress","done"],"swimlanes":false}', 'productivity', 1234),
('Team Calendar', 'calendar', 'Shared calendar with meeting and deadline overlay', 'calendar-api', '{"view":"month","showWeekNumbers":true}', 'collaboration', 678),
('Deployment Timeline', 'timeline', 'CI/CD deployment history and upcoming releases', 'devops-api', '{"environments":["staging","prod"],"lookback":"7d"}', 'devops', 445),
('KPI Metric Card', 'metric', 'Single metric display with trend indicator', 'metrics-api', '{"metric":"","comparison":"prev_period","format":"number"}', 'analytics', 2103),
('User Feedback Form', 'form', 'Embedded feedback collection with NPS scoring', 'feedback-api', '{"fields":["nps","comment","category"],"trigger":"manual"}', 'engagement', 234),
('Activity Feed', 'feed', 'Real-time team activity stream with filtering', 'activity-api', '{"limit":50,"filters":["user","action","resource"]}', 'collaboration', 567),
('Data Table', 'table', 'Sortable, filterable data table with export', 'data-api', '{"columns":[],"pageSize":25,"exportFormats":["csv","xlsx"]}', 'data', 1567),
('Burndown Chart', 'chart', 'Sprint burndown visualization for agile teams', 'sprints-api', '{"sprintId":null,"showIdeal":true}', 'agile', 389),
('Quick Notes', 'form', 'Sticky note widget for quick capture', 'notes-api', '{"maxLength":500,"colors":["yellow","blue","green"]}', 'productivity', 876),
('PR Review Queue', 'table', 'Open pull requests with review status', 'github-api', '{"repo":"","assignedToMe":true,"draft":false}', 'devops', 723),
('Meeting Scheduler', 'calendar', 'Smart meeting scheduler with availability detection', 'calendar-api', '{"duration":30,"buffer":5,"timezone":"auto"}', 'collaboration', 312),
('Color Palette Picker', 'chart', 'Design token color palette management and preview', 'design-api', '{"tokens":[],"format":"hex"}', 'design', 198),
('Project Progress', 'metric', 'Multi-milestone project completion tracker', 'projects-api', '{"showMilestones":true,"completionMetric":"tasks"}', 'productivity', 634),
('Error Monitoring', 'feed', 'Real-time application error stream with severity levels', 'monitoring-api', '{"severity":["error","critical"],"groupSimilar":true}', 'devops', 456)
ON CONFLICT DO NOTHING;

INSERT INTO ui_sessions (ui_user_id, started_at, ended_at, duration_mins, layout_used, actions_count, satisfaction_rating, device_type) VALUES
(1, NOW() - INTERVAL '1 day', NOW() - INTERVAL '1 day' + INTERVAL '2 hours', 120, 'dashboard', 156, 5, 'desktop'),
(2, NOW() - INTERVAL '2 days', NOW() - INTERVAL '2 days' + INTERVAL '45 minutes', 45, 'kanban', 43, 4, 'laptop'),
(3, NOW() - INTERVAL '1 day', NOW() - INTERVAL '1 day' + INTERVAL '30 minutes', 30, 'calendar', 28, 4, 'tablet'),
(4, NOW() - INTERVAL '3 days', NOW() - INTERVAL '3 days' + INTERVAL '90 minutes', 90, 'grid', 89, 5, 'desktop'),
(5, NOW() - INTERVAL '1 day', NOW() - INTERVAL '1 day' + INTERVAL '3 hours', 180, 'timeline', 234, 4, 'desktop'),
(6, NOW() - INTERVAL '2 days', NOW() - INTERVAL '2 days' + INTERVAL '2 hours', 120, 'tasklist', 178, 5, 'desktop'),
(7, NOW() - INTERVAL '4 days', NOW() - INTERVAL '4 days' + INTERVAL '25 minutes', 25, 'dashboard', 18, 3, 'laptop'),
(8, NOW() - INTERVAL '1 day', NOW() - INTERVAL '1 day' + INTERVAL '1 hour', 60, 'grid', 67, 5, 'desktop'),
(9, NOW() - INTERVAL '5 days', NOW() - INTERVAL '5 days' + INTERVAL '4 hours', 240, 'dashboard', 312, 4, 'desktop'),
(10, NOW() - INTERVAL '2 days', NOW() - INTERVAL '2 days' + INTERVAL '1 hour', 60, 'calendar', 45, 4, 'tablet'),
(11, NOW() - INTERVAL '6 days', NOW() - INTERVAL '6 days' + INTERVAL '2 hours', 120, 'timeline', 145, 5, 'desktop'),
(12, NOW() - INTERVAL '1 day', NOW() - INTERVAL '1 day' + INTERVAL '3 hours', 180, 'kanban', 267, 4, 'laptop'),
(13, NOW() - INTERVAL '3 days', NOW() - INTERVAL '3 days' + INTERVAL '90 minutes', 90, 'dashboard', 123, 4, 'desktop'),
(1, NOW() - INTERVAL '8 days', NOW() - INTERVAL '8 days' + INTERVAL '2 hours', 120, 'dashboard', 189, 5, 'desktop'),
(6, NOW() - INTERVAL '5 days', NOW() - INTERVAL '5 days' + INTERVAL '1 hour', 60, 'tasklist', 98, 5, 'desktop')
ON CONFLICT DO NOTHING;

INSERT INTO customizations (ui_user_id, config_name, config_json, is_active, description, last_used) VALUES
(1, 'Morning Dashboard', '{"widgets":["kpi-summary","pr-queue","deployment-status"],"theme":"dark","density":"compact"}', true, 'Optimized morning startup view', NOW() - INTERVAL '1 day'),
(2, 'Sprint Planning Mode', '{"widgets":["kanban","burndown","team-capacity"],"density":"comfortable"}', true, 'Weekly sprint planning setup', NOW() - INTERVAL '3 days'),
(3, 'Study Session', '{"widgets":["calendar","timer","notes"],"theme":"light","density":"spacious"}', true, 'Distraction-free study mode', NOW() - INTERVAL '2 days'),
(4, 'Design Review', '{"widgets":["asset-grid","component-browser","color-palette"],"theme":"dark"}', true, 'Design review and critique mode', NOW() - INTERVAL '4 days'),
(5, 'Team Standup', '{"widgets":["team-status","blockers","sprint-progress"],"density":"compact"}', true, 'Daily standup view', NOW() - INTERVAL '1 day'),
(6, 'Deep Work Mode', '{"widgets":["current-task","timer","code-review"],"hideNav":true}', true, 'Focused development sessions', NOW() - INTERVAL '2 days'),
(7, 'Executive Briefing', '{"widgets":["daily-digest","financial-kpi","risk-alerts"],"theme":"light"}', false, 'Deprecated morning briefing', NOW() - INTERVAL '30 days'),
(8, 'Component Audit', '{"widgets":["design-system","accessibility-checker","usage-stats"]}', true, 'Monthly design system audit', NOW() - INTERVAL '7 days'),
(9, 'Board Meeting Prep', '{"widgets":["financial-summary","growth-metrics","investor-kpis"],"density":"comfortable"}', true, 'Quarterly board preparation', NOW() - INTERVAL '5 days'),
(11, 'Architecture Review', '{"widgets":["system-diagram","performance-metrics","dependency-graph"],"density":"compact"}', true, 'Weekly architecture review', NOW() - INTERVAL '6 days'),
(12, 'Project Tracking', '{"widgets":["gantt","milestones","resource-allocation"],"theme":"light"}', true, 'Cross-team project tracking', NOW() - INTERVAL '1 day'),
(1, 'Incident Response', '{"widgets":["alerts","error-feed","deployment-rollback"],"density":"compact","alerts":true}', false, 'On-call incident response mode', NOW() - INTERVAL '15 days'),
(6, 'Code Review Focus', '{"widgets":["open-prs","diff-view","test-results"],"compact":true}', true, 'Efficient code review flow', NOW() - INTERVAL '1 day'),
(4, 'Client Presentation', '{"widgets":["design-showcase","brand-guidelines","portfolio"],"theme":"light","density":"spacious"}', true, 'Client presentation mode', NOW() - INTERVAL '10 days'),
(13, 'Demo Mode', '{"widgets":["feature-showcase","metrics","customer-success"],"theme":"dark"}', true, 'Sales demo configuration', NOW() - INTERVAL '2 days')
ON CONFLICT DO NOTHING;

INSERT INTO feedback (ui_user_id, template_id, rating, category, comments, status) VALUES
(1, 1, 5, 'usability', 'The compact dashboard is exactly what I need. Keyboard shortcuts work perfectly.', 'reviewed'),
(2, 6, 4, 'functionality', 'Good kanban view. Would love better sprint velocity tracking built in.', 'reviewed'),
(3, 4, 4, 'design', 'Calendar view is intuitive. Could use better mobile support.', 'new'),
(4, 5, 5, 'design', 'Best template for design work. The asset grid is exceptional.', 'reviewed'),
(5, 7, 3, 'functionality', 'Timeline needs more Gantt features. Dependencies are hard to visualize.', 'new'),
(6, 3, 5, 'usability', 'Developer tasklist is a game changer. PR integration is seamless.', 'reviewed'),
(7, 2, 4, 'design', 'Clean executive view. Sometimes too minimal - need more context.', 'reviewed'),
(8, 5, 5, 'design', 'Incredible canvas grid for design work. Would add more design tokens.', 'new'),
(9, 14, 5, 'functionality', 'Executive briefing template saves me 30 minutes every morning.', 'reviewed'),
(10, 4, 4, 'usability', 'Calendar view is perfect for students. Assignment integration would be great.', 'new'),
(11, 12, 4, 'functionality', 'DevOps pipeline view is solid. Needs better alert configuration.', 'reviewed'),
(12, 6, 4, 'design', 'Great kanban layout for managing multiple teams.', 'reviewed'),
(1, 9, 5, 'functionality', 'Analytics dashboard pro is incredible. Best data viz template available.', 'reviewed'),
(6, 15, 5, 'usability', 'Compact code review template boosted my review speed by 40%.', 'new'),
(13, 1, 4, 'functionality', 'Power user dashboard is great for demos. Would add more customization options.', 'new')
ON CONFLICT DO NOTHING;

-- =====================================================
-- DEEP FEATURES SEED DATA (2026-05-14)
-- =====================================================

-- INTENT NODES (intent graph: what users want to accomplish, not screens)
INSERT INTO intent_nodes (slug, label, description, category, signal_keywords, expected_components, trigger_count, success_rate, median_completion_ms) VALUES
('triage-inbox', 'Triage inbox', 'Quickly process unread/urgent items and decide action', 'decide', 'inbox,unread,clear,triage,urgent', '["shadcn-data-table","radix-context-menu","shadcn-toast"]', 14820, 0.812, 7400),
('compose-async-update', 'Compose async update', 'Write a structured status update for the team', 'communicate', 'write,update,status,post,share', '["shadcn-textarea","tiptap-editor","radix-popover"]', 4318, 0.764, 22100),
('investigate-incident', 'Investigate incident', 'Diagnose a production incident with logs and metrics', 'decide', 'incident,error,pager,outage,debug', '["recharts-line","shadcn-data-table","radix-tabs","shadcn-command"]', 962, 0.587, 184000),
('review-pull-request', 'Review pull request', 'Read diff, comment, approve or request changes', 'decide', 'pr,review,diff,approve,changes', '["shadcn-data-table","monaco-editor","radix-popover"]', 8311, 0.873, 41200),
('plan-sprint', 'Plan upcoming sprint', 'Move backlog items into next sprint with capacity', 'configure', 'sprint,plan,backlog,capacity', '["ag-grid-kanban","shadcn-slider","recharts-bar"]', 2104, 0.701, 96000),
('check-kpis', 'Check KPIs', 'See current state of headline KPIs and trends', 'monitor', 'kpi,metric,number,how-are-we', '["recharts-line","tremor-kpi-card","shadcn-tabs"]', 11240, 0.918, 4300),
('build-dashboard', 'Build a dashboard', 'Compose a multi-widget dashboard for a topic', 'create', 'build,assemble,dashboard,custom', '["ag-grid-pivot","recharts-line","shadcn-resizable"]', 1873, 0.642, 380000),
('schedule-meeting', 'Schedule meeting', 'Find a time and invite attendees', 'communicate', 'meeting,schedule,book,invite', '["radix-calendar","shadcn-combobox","shadcn-form"]', 5419, 0.844, 28000),
('debug-slow-query', 'Debug slow query', 'Find query plans, latency hotspots, suggest indexes', 'decide', 'slow,query,latency,explain,index', '["recharts-area","shadcn-data-table","monaco-editor"]', 412, 0.523, 220000),
('approve-expense', 'Approve expense', 'Review and approve/deny an expense submission', 'decide', 'expense,approve,reimburse,receipt', '["shadcn-data-table","radix-dialog","shadcn-form"]', 1742, 0.892, 6200),
('triage-inbox-snooze', 'Snooze inbox item', 'Defer an item to a later time', 'configure', 'snooze,later,defer,remind', '["radix-calendar","shadcn-button"]', 3104, 0.881, 3100),
('compose-doc', 'Author a long document', 'Long-form writing with rich text and embeds', 'create', 'doc,write,page,article', '["tiptap-editor","shadcn-toolbar"]', 2218, 0.732, 1200000)
ON CONFLICT (slug) DO NOTHING;

-- INTENT EDGES (transitions between intents)
INSERT INTO intent_edges (from_intent_id, to_intent_id, edge_type, transition_count, avg_dwell_ms) VALUES
(1, 11, 'branches', 2841, 2800),
(1, 2, 'follows', 1820, 18200),
(1, 8, 'follows', 940, 9100),
(3, 9, 'refines', 312, 124000),
(3, 6, 'escalates', 187, 4100),
(4, 2, 'follows', 4520, 21300),
(5, 6, 'follows', 1421, 5300),
(7, 6, 'follows', 901, 12400),
(8, 2, 'follows', 1320, 22000),
(2, 12, 'refines', 480, 92000)
ON CONFLICT DO NOTHING;

-- COMPONENT PRIMITIVES (real shadcn/Radix/AG Grid/Recharts/Tremor)
INSERT INTO component_primitives (slug, display_name, library, category, description, prop_schema, default_props, example_jsx, docs_url, supports_rsc, a11y_role, bundle_kb, usage_count) VALUES
('shadcn-data-table', 'shadcn Data Table', 'shadcn', 'display', 'Type-safe table built on @tanstack/react-table with shadcn styling',
 '{"type":"object","properties":{"columns":{"type":"array"},"data":{"type":"array"},"pagination":{"type":"boolean"}}}'::jsonb,
 '{"pagination":true}'::jsonb,
 '<DataTable columns={columns} data={data} pagination />',
 'https://ui.shadcn.com/docs/components/data-table', true, 'grid', 14.20, 4218),
('shadcn-command', 'shadcn Command Palette', 'shadcn', 'overlay', 'cmdk-based command menu (Cmd+K)',
 '{"type":"object","properties":{"open":{"type":"boolean"},"placeholder":{"type":"string"}}}'::jsonb,
 '{"placeholder":"Type a command..."}'::jsonb,
 '<CommandDialog open={open}><CommandInput /><CommandList>...</CommandList></CommandDialog>',
 'https://ui.shadcn.com/docs/components/command', true, 'dialog', 6.80, 2914),
('shadcn-resizable', 'shadcn Resizable Panels', 'shadcn', 'navigation', 'react-resizable-panels wrapper',
 '{"type":"object","properties":{"direction":{"enum":["horizontal","vertical"]}}}'::jsonb,
 '{"direction":"horizontal"}'::jsonb,
 '<ResizablePanelGroup direction="horizontal">...</ResizablePanelGroup>',
 'https://ui.shadcn.com/docs/components/resizable', true, 'separator', 3.10, 612),
('shadcn-form', 'shadcn Form (react-hook-form + zod)', 'shadcn', 'input', 'Composable form primitive with zod validation',
 '{"type":"object","properties":{"schema":{"type":"object"}}}'::jsonb,
 '{}'::jsonb,
 '<Form {...form}><FormField .../></Form>',
 'https://ui.shadcn.com/docs/components/form', false, 'form', 4.50, 3120),
('radix-dialog', 'Radix Dialog', 'radix', 'overlay', 'Modal dialog primitive with focus trap',
 '{"type":"object","properties":{"open":{"type":"boolean"},"modal":{"type":"boolean"}}}'::jsonb,
 '{"modal":true}'::jsonb,
 '<Dialog.Root open={open}><Dialog.Content>...</Dialog.Content></Dialog.Root>',
 'https://www.radix-ui.com/primitives/docs/components/dialog', false, 'dialog', 3.40, 5821),
('radix-popover', 'Radix Popover', 'radix', 'overlay', 'Floating UI popover with arrow + focus return',
 '{"type":"object","properties":{"side":{"enum":["top","bottom","left","right"]}}}'::jsonb,
 '{"side":"bottom"}'::jsonb,
 '<Popover.Root><Popover.Trigger>...</Popover.Trigger></Popover.Root>',
 'https://www.radix-ui.com/primitives/docs/components/popover', false, 'dialog', 2.90, 3412),
('radix-tabs', 'Radix Tabs', 'radix', 'navigation', 'WAI-ARIA tabs with roving tabindex',
 '{"type":"object","properties":{"defaultValue":{"type":"string"}}}'::jsonb,
 '{}'::jsonb,
 '<Tabs.Root defaultValue="overview"><Tabs.List>...</Tabs.List></Tabs.Root>',
 'https://www.radix-ui.com/primitives/docs/components/tabs', false, 'tablist', 1.80, 4910),
('radix-calendar', 'Radix Calendar (date)', 'radix', 'input', 'Date-picker calendar primitive',
 '{"type":"object","properties":{"value":{"type":"string"},"min":{"type":"string"}}}'::jsonb,
 '{}'::jsonb,
 '<Calendar value={d} onValueChange={setD} />',
 'https://www.radix-ui.com/primitives/docs/components/calendar', false, 'application', 5.10, 1240),
('radix-context-menu', 'Radix Context Menu', 'radix', 'overlay', 'Right-click context menu primitive',
 '{"type":"object","properties":{"items":{"type":"array"}}}'::jsonb,
 '{}'::jsonb,
 '<ContextMenu.Root><ContextMenu.Trigger>...</ContextMenu.Trigger></ContextMenu.Root>',
 'https://www.radix-ui.com/primitives/docs/components/context-menu', false, 'menu', 2.20, 1812),
('ag-grid-pivot', 'AG Grid Pivot', 'ag-grid', 'grid', 'Enterprise data grid with pivot, group, aggregation',
 '{"type":"object","properties":{"columnDefs":{"type":"array"},"pivotMode":{"type":"boolean"}}}'::jsonb,
 '{"pivotMode":true}'::jsonb,
 '<AgGridReact columnDefs={cols} pivotMode />',
 'https://www.ag-grid.com/react-data-grid/pivoting/', false, 'grid', 480.00, 712),
('ag-grid-kanban', 'AG Grid Kanban (row-grouping)', 'ag-grid', 'grid', 'Row-grouping kanban view via AG Grid',
 '{"type":"object","properties":{"groupBy":{"type":"string"}}}'::jsonb,
 '{}'::jsonb,
 '<AgGridReact rowGroupPanelShow="always" />',
 'https://www.ag-grid.com/react-data-grid/row-grouping/', false, 'grid', 480.00, 318),
('recharts-line', 'Recharts LineChart', 'recharts', 'chart', 'SVG line chart',
 '{"type":"object","properties":{"data":{"type":"array"},"xKey":{"type":"string"},"yKey":{"type":"string"}}}'::jsonb,
 '{}'::jsonb,
 '<LineChart data={data}><Line dataKey="value" /></LineChart>',
 'https://recharts.org/en-US/api/LineChart', false, 'img', 92.00, 3814),
('recharts-area', 'Recharts AreaChart', 'recharts', 'chart', 'Stacked area chart',
 '{"type":"object","properties":{"data":{"type":"array"}}}'::jsonb,
 '{}'::jsonb,
 '<AreaChart data={data}><Area dataKey="value" /></AreaChart>',
 'https://recharts.org/en-US/api/AreaChart', false, 'img', 92.00, 1410),
('recharts-bar', 'Recharts BarChart', 'recharts', 'chart', 'Vertical/horizontal bars',
 '{"type":"object","properties":{"data":{"type":"array"}}}'::jsonb,
 '{}'::jsonb,
 '<BarChart data={data}><Bar dataKey="value" /></BarChart>',
 'https://recharts.org/en-US/api/BarChart', false, 'img', 92.00, 2218),
('tremor-kpi-card', 'Tremor KPI Card', 'tremor', 'display', 'Single-metric KPI card with delta',
 '{"type":"object","properties":{"metric":{"type":"string"},"value":{"type":"number"},"delta":{"type":"number"}}}'::jsonb,
 '{}'::jsonb,
 '<Card><Text>{metric}</Text><Metric>{value}</Metric><BadgeDelta>{delta}</BadgeDelta></Card>',
 'https://www.tremor.so/docs/components/kpi-cards', true, 'group', 18.40, 4120),
('tiptap-editor', 'Tiptap Rich-Text Editor', 'tiptap', 'input', 'ProseMirror-based rich-text editor',
 '{"type":"object","properties":{"extensions":{"type":"array"},"content":{"type":"string"}}}'::jsonb,
 '{}'::jsonb,
 '<EditorContent editor={editor} />',
 'https://tiptap.dev/docs/editor/api/editor', false, 'textbox', 86.00, 1820),
('monaco-editor', 'Monaco Editor', 'custom', 'input', 'VS Code editor in the browser',
 '{"type":"object","properties":{"language":{"type":"string"},"value":{"type":"string"}}}'::jsonb,
 '{"language":"typescript"}'::jsonb,
 '<Editor language="typescript" value={code} />',
 'https://microsoft.github.io/monaco-editor/', false, 'textbox', 1240.00, 920),
('shadcn-toast', 'shadcn Toast (sonner)', 'shadcn', 'feedback', 'Stacked toast notifications',
 '{"type":"object","properties":{"position":{"enum":["top","bottom","top-right"]}}}'::jsonb,
 '{"position":"bottom"}'::jsonb,
 '<Toaster /> // toast.success("Saved")',
 'https://ui.shadcn.com/docs/components/sonner', true, 'status', 5.30, 4612),
('shadcn-combobox', 'shadcn Combobox', 'shadcn', 'input', 'cmdk + popover combobox',
 '{"type":"object","properties":{"options":{"type":"array"}}}'::jsonb,
 '{}'::jsonb,
 '<Combobox options={opts} value={v} onChange={setV} />',
 'https://ui.shadcn.com/docs/components/combobox', false, 'combobox', 7.10, 2014),
('shadcn-slider', 'shadcn Slider', 'shadcn', 'input', 'Radix-Slider-based slider',
 '{"type":"object","properties":{"min":{"type":"number"},"max":{"type":"number"}}}'::jsonb,
 '{"min":0,"max":100}'::jsonb,
 '<Slider min={0} max={100} value={[v]} onValueChange={([n])=>setV(n)} />',
 'https://ui.shadcn.com/docs/components/slider', false, 'slider', 1.40, 612),
('shadcn-tabs', 'shadcn Tabs', 'shadcn', 'navigation', 'Tabs wrapper over Radix Tabs',
 '{"type":"object","properties":{"defaultValue":{"type":"string"}}}'::jsonb,
 '{}'::jsonb,
 '<Tabs defaultValue="a"><TabsList>...</TabsList></Tabs>',
 'https://ui.shadcn.com/docs/components/tabs', false, 'tablist', 2.10, 3120),
('shadcn-toolbar', 'shadcn Toolbar', 'shadcn', 'navigation', 'Editor toolbar primitive',
 '{"type":"object","properties":{"items":{"type":"array"}}}'::jsonb,
 '{}'::jsonb,
 '<Toolbar.Root>...</Toolbar.Root>',
 'https://www.radix-ui.com/primitives/docs/components/toolbar', false, 'toolbar', 2.60, 410),
('shadcn-textarea', 'shadcn Textarea', 'shadcn', 'input', 'Styled textarea primitive',
 '{"type":"object","properties":{"rows":{"type":"number"}}}'::jsonb,
 '{"rows":4}'::jsonb,
 '<Textarea rows={4} placeholder="Write..." />',
 'https://ui.shadcn.com/docs/components/textarea', true, 'textbox', 0.80, 4012)
ON CONFLICT (slug) DO NOTHING;

-- DESIGN TOKENS (Tailwind + Radix + shadcn convention)
INSERT INTO design_tokens (token_key, token_value, category, tier, ref_token_key, source, description, dark_mode_value) VALUES
('color.brand.500', '#6366f1', 'color', 'primitive', NULL, 'tailwind', 'Indigo-500 brand primary', '#818cf8'),
('color.brand.600', '#4f46e5', 'color', 'primitive', NULL, 'tailwind', 'Indigo-600 brand hover', '#6366f1'),
('color.gray.50', '#f9fafb', 'color', 'primitive', NULL, 'tailwind', 'Gray-50', '#0a0a0a'),
('color.gray.900', '#111827', 'color', 'primitive', NULL, 'tailwind', 'Gray-900', '#f9fafb'),
('color.danger.500', '#ef4444', 'color', 'primitive', NULL, 'tailwind', 'Red-500 danger', '#f87171'),
('color.success.500', '#22c55e', 'color', 'primitive', NULL, 'tailwind', 'Green-500 success', '#4ade80'),
('color.warning.500', '#f59e0b', 'color', 'primitive', NULL, 'tailwind', 'Amber-500 warning', '#fbbf24'),
('color.surface.default', 'var(--color-gray-50)', 'color', 'semantic', 'color.gray.50', 'shadcn', 'Default surface bg', 'var(--color-gray-900)'),
('color.surface.elevated', '#ffffff', 'color', 'semantic', NULL, 'shadcn', 'Elevated card bg', '#1f2937'),
('color.text.primary', 'var(--color-gray-900)', 'color', 'semantic', 'color.gray.900', 'shadcn', 'Primary text', 'var(--color-gray-50)'),
('color.button.primary.bg', 'var(--color-brand-600)', 'color', 'component', 'color.brand.600', 'shadcn', 'Primary button bg', 'var(--color-brand-500)'),
('radius.sm', '0.25rem', 'radius', 'primitive', NULL, 'tailwind', '4px small radius', NULL),
('radius.md', '0.5rem', 'radius', 'primitive', NULL, 'tailwind', '8px medium radius', NULL),
('radius.lg', '0.75rem', 'radius', 'primitive', NULL, 'tailwind', '12px large radius', NULL),
('radius.xl', '1rem', 'radius', 'primitive', NULL, 'tailwind', '16px x-large radius', NULL),
('shadow.sm', '0 1px 2px 0 rgb(0 0 0 / 0.05)', 'shadow', 'primitive', NULL, 'tailwind', 'Small shadow', NULL),
('shadow.md', '0 4px 6px -1px rgb(0 0 0 / 0.1)', 'shadow', 'primitive', NULL, 'tailwind', 'Medium shadow', NULL),
('spacing.1', '0.25rem', 'spacing', 'primitive', NULL, 'tailwind', '4px', NULL),
('spacing.2', '0.5rem', 'spacing', 'primitive', NULL, 'tailwind', '8px', NULL),
('spacing.4', '1rem', 'spacing', 'primitive', NULL, 'tailwind', '16px', NULL),
('spacing.8', '2rem', 'spacing', 'primitive', NULL, 'tailwind', '32px', NULL),
('font.sans', 'Inter, ui-sans-serif, system-ui', 'font', 'primitive', NULL, 'tailwind', 'Sans-serif stack', NULL),
('font.mono', 'JetBrains Mono, ui-monospace', 'font', 'primitive', NULL, 'tailwind', 'Monospace stack', NULL),
('motion.ease.out', 'cubic-bezier(0,0,0.2,1)', 'motion', 'primitive', NULL, 'radix', 'Ease-out curve', NULL),
('z.modal', '50', 'z', 'semantic', NULL, 'radix', 'Modal z-index', NULL),
('z.toast', '60', 'z', 'semantic', NULL, 'radix', 'Toast z-index', NULL)
ON CONFLICT (token_key) DO NOTHING;

-- LAYOUT VARIANTS (one control + 1-2 variants per major intent)
INSERT INTO layout_variants (intent_id, variant_key, hypothesis, primitives_json, layout_json, copy_tone, density, is_control, is_active, traffic_pct) VALUES
(1, 'v1-control-list', 'Linear list is the safe baseline for inbox triage', '["shadcn-data-table","radix-context-menu"]'::jsonb, '{"areas":["list"],"cols":1}'::jsonb, 'terse', 'compact', true, true, 50),
(1, 'v2-split-preview', 'Hypothesis: split list+preview reduces clicks by 30%', '["shadcn-resizable","shadcn-data-table","radix-tabs"]'::jsonb, '{"areas":["list","preview"],"cols":2}'::jsonb, 'terse', 'compact', false, true, 50),
(3, 'v1-control-logs', 'Logs-first layout is the default incident view', '["shadcn-data-table","recharts-line"]'::jsonb, '{"areas":["logs","chart"],"cols":1}'::jsonb, 'terse', 'compact', true, true, 33),
(3, 'v2-chart-first', 'Hypothesis: chart-first speeds detection of regressions', '["recharts-line","shadcn-data-table"]'::jsonb, '{"areas":["chart","logs"],"cols":1}'::jsonb, 'terse', 'compact', false, true, 33),
(3, 'v3-command-overlay', 'Hypothesis: Cmd+K driven incident triage for SREs', '["shadcn-command","recharts-line","shadcn-data-table"]'::jsonb, '{"areas":["palette","chart","logs"],"cols":2}'::jsonb, 'terse', 'compact', false, true, 34),
(6, 'v1-tiles', 'KPI tiles in a 4-up grid (control)', '["tremor-kpi-card","recharts-line"]'::jsonb, '{"areas":["tiles","trend"],"cols":4}'::jsonb, 'formal', 'comfortable', true, true, 50),
(6, 'v2-narrative', 'Hypothesis: narrative summary above tiles increases comprehension', '["shadcn-textarea","tremor-kpi-card","recharts-line"]'::jsonb, '{"areas":["summary","tiles","trend"],"cols":2}'::jsonb, 'conversational', 'comfortable', false, true, 50),
(7, 'v1-pivot', 'Pivot grid for builders (control)', '["ag-grid-pivot","recharts-line"]'::jsonb, '{"areas":["pivot","chart"],"cols":2}'::jsonb, 'terse', 'compact', true, true, 60),
(7, 'v2-resizable-trio', 'Hypothesis: resizable trio better for power users', '["shadcn-resizable","ag-grid-pivot","recharts-line","tremor-kpi-card"]'::jsonb, '{"areas":["pivot","chart","tiles"],"cols":3}'::jsonb, 'terse', 'compact', false, true, 40)
ON CONFLICT DO NOTHING;

-- VARIANT TELEMETRY (one row per variant per recent date)
INSERT INTO variant_telemetry (variant_id, ui_user_id, impressions, task_completions, conversions, bounce_count, avg_time_to_first_action_ms, avg_task_completion_ms, recorded_for) VALUES
(1, NULL, 8214, 6310, 5872, 410, 1820, 7400, CURRENT_DATE - 1),
(2, NULL, 8190, 7104, 6841, 286, 1240, 5200, CURRENT_DATE - 1),
(1, NULL, 9012, 7012, 6510, 480, 1740, 7220, CURRENT_DATE - 2),
(2, NULL, 8980, 7820, 7421, 312, 1180, 5040, CURRENT_DATE - 2),
(3, NULL, 412, 245, 220, 41, 4200, 188000, CURRENT_DATE - 1),
(4, NULL, 401, 268, 240, 38, 3100, 144000, CURRENT_DATE - 1),
(5, NULL, 410, 312, 290, 22, 2400, 121000, CURRENT_DATE - 1),
(6, NULL, 7102, 6510, 6120, 240, 920, 4300, CURRENT_DATE - 1),
(7, NULL, 7088, 6710, 6380, 198, 880, 4100, CURRENT_DATE - 1),
(8, NULL, 1241, 820, 712, 142, 5800, 380000, CURRENT_DATE - 1),
(9, NULL, 1219, 891, 802, 98, 4900, 320000, CURRENT_DATE - 1)
ON CONFLICT DO NOTHING;

-- UI GENERATION RUNS (generative-UI history)
INSERT INTO ui_generation_runs (intent_id, ui_user_id, model, sdk, prompt, generated_jsx, primitives_used, tokens_in, tokens_out, latency_ms, cost_usd, humaneval_pass, componentbench_score, swebench_style_score, a11y_score, status) VALUES
(1, 1, 'anthropic/claude-opus-4.7', 'vercel-ai-sdk', 'Build a dense inbox triage list with keyboard shortcuts',
 '<DataTable columns={inboxCols} data={mail} pagination={false} dense />',
 '["shadcn-data-table","radix-context-menu"]'::jsonb, 1820, 412, 2140, 0.04510, true, 0.910, 0.864, 0.940, 'success'),
(1, 2, 'openai/gpt-4o', 'vercel-ai-sdk', 'Inbox triage with side preview pane',
 '<ResizablePanelGroup direction="horizontal"><ResizablePanel><DataTable .../></ResizablePanel><ResizablePanel>preview</ResizablePanel></ResizablePanelGroup>',
 '["shadcn-resizable","shadcn-data-table"]'::jsonb, 1944, 521, 2810, 0.02112, true, 0.882, 0.821, 0.910, 'success'),
(3, 5, 'anthropic/claude-opus-4.7', 'anthropic-sdk', 'Incident chart-first with annotated regressions',
 '<LineChart data={errRate}><Line dataKey="errors" /></LineChart><DataTable columns={logCols} data={logs} />',
 '["recharts-line","shadcn-data-table"]'::jsonb, 2410, 612, 3120, 0.05210, true, 0.864, 0.792, 0.880, 'success'),
(6, 7, 'anthropic/claude-haiku-4.5', 'openrouter', 'Executive KPI cards 4 across with sparklines',
 '<Grid cols={4}><KpiCard metric="ARR" .../><KpiCard metric="MAU" .../></Grid>',
 '["tremor-kpi-card","recharts-line"]'::jsonb, 1320, 318, 1180, 0.00420, true, 0.921, 0.842, 0.960, 'success'),
(7, 4, 'anthropic/claude-opus-4.7', 'vercel-ai-sdk', 'Pivot dashboard for product analytics with funnel',
 '<AgGridReact columnDefs={cols} pivotMode />',
 '["ag-grid-pivot","recharts-line"]'::jsonb, 2840, 720, 4120, 0.06210, true, 0.842, 0.764, 0.870, 'success'),
(4, 6, 'openai/gpt-4o-mini', 'vercel-ai-sdk', 'PR review queue with bulk actions',
 '<DataTable columns={prCols} data={prs} />',
 '["shadcn-data-table","radix-context-menu"]'::jsonb, 1410, 280, 920, 0.00610, true, 0.892, 0.831, 0.910, 'success'),
(8, 2, 'anthropic/claude-opus-4.7', 'vercel-ai-sdk', 'Meeting scheduler with combobox attendees and calendar',
 '<Form><Combobox .../><Calendar .../></Form>',
 '["shadcn-form","shadcn-combobox","radix-calendar"]'::jsonb, 1620, 420, 2240, 0.04210, true, 0.901, 0.842, 0.930, 'success'),
(2, 1, 'anthropic/claude-opus-4.7', 'vercel-ai-sdk', 'Async update composer with mention support',
 '<EditorContent editor={tiptap} /><Toolbar.Root>...</Toolbar.Root>',
 '["tiptap-editor","shadcn-toolbar"]'::jsonb, 1240, 540, 2810, 0.04812, true, 0.872, 0.812, 0.890, 'success'),
(9, 5, 'anthropic/claude-opus-4.7', 'vercel-ai-sdk', 'Slow query debugger: area chart of latency + explain plan editor',
 '<AreaChart data={lat} /><Editor language="sql" value={plan} />',
 '["recharts-area","monaco-editor","shadcn-data-table"]'::jsonb, 2810, 680, 3640, 0.06820, true, 0.821, 0.741, 0.840, 'success'),
(5, 12, 'anthropic/claude-haiku-4.5', 'openrouter', 'Sprint planning kanban with capacity slider',
 '<AgGridReact rowGroupPanelShow="always" /><Slider min={0} max={40} />',
 '["ag-grid-kanban","shadcn-slider","recharts-bar"]'::jsonb, 1820, 412, 1320, 0.00510, true, 0.864, 0.792, 0.910, 'success'),
(10, 9, 'openai/gpt-4o', 'vercel-ai-sdk', 'Expense approval list with detail dialog',
 '<DataTable ... /><Dialog.Root>...</Dialog.Root>',
 '["shadcn-data-table","radix-dialog","shadcn-form"]'::jsonb, 1410, 312, 1820, 0.01320, true, 0.910, 0.854, 0.940, 'success'),
(3, 11, 'meta-llama/llama-3.3-70b', 'openrouter', 'Incident: tabbed metrics view',
 '<Tabs.Root defaultValue="errors"><Tabs.List>...</Tabs.List></Tabs.Root>',
 '["radix-tabs","recharts-line"]'::jsonb, 1820, 412, 4810, 0.00210, false, 0.642, 0.521, 0.720, 'flagged'),
(7, 8, 'anthropic/claude-opus-4.7', 'vercel-ai-sdk', 'Designer-friendly token swatch grid + chart',
 '<Grid>{tokens.map(t=><Swatch .../>)}</Grid>',
 '["shadcn-resizable","recharts-bar"]'::jsonb, 1320, 280, 1810, 0.03210, true, 0.832, 0.764, 0.880, 'success'),
(12, 1, 'anthropic/claude-opus-4.7', 'vercel-ai-sdk', 'Long-form doc editor with TOC',
 '<EditorContent editor={editor} /><nav>TOC</nav>',
 '["tiptap-editor","shadcn-tabs"]'::jsonb, 1640, 520, 2410, 0.04210, true, 0.881, 0.821, 0.910, 'success'),
(11, 3, 'anthropic/claude-haiku-4.5', 'openrouter', 'Snooze popover with calendar quick-pick',
 '<Popover.Root><Popover.Content><Calendar .../></Popover.Content></Popover.Root>',
 '["radix-popover","radix-calendar"]'::jsonb, 920, 180, 720, 0.00210, true, 0.910, 0.872, 0.940, 'success')
ON CONFLICT DO NOTHING;

-- INTENT CLASSIFIER FEW-SHOT EXAMPLES (training + dev splits)
INSERT INTO intent_classifier_examples (intent_id, utterance, context_json, expected_output, split, confidence_observed, is_correct) VALUES
(1, 'clear my unread', '{"role":"executive","time":"09:00","recent":["open-inbox"]}'::jsonb,
 '{"intent":"triage-inbox","params":{"filter":"unread"},"confidence":0.94}'::jsonb, 'train', 0.940, true),
(1, 'show me what needs my attention', '{"role":"manager","time":"08:30"}'::jsonb,
 '{"intent":"triage-inbox","params":{"filter":"urgent"},"confidence":0.88}'::jsonb, 'train', 0.880, true),
(1, 'inbox zero now', '{}'::jsonb,
 '{"intent":"triage-inbox","params":{},"confidence":0.91}'::jsonb, 'dev', 0.910, true),
(2, 'post an update about the sprint', '{"role":"manager"}'::jsonb,
 '{"intent":"compose-async-update","params":{"topic":"sprint"},"confidence":0.93}'::jsonb, 'train', 0.930, true),
(2, 'share status with the team', '{}'::jsonb,
 '{"intent":"compose-async-update","params":{},"confidence":0.87}'::jsonb, 'dev', 0.870, true),
(3, 'why is the API slow', '{"role":"developer","recent":["pager-alert"]}'::jsonb,
 '{"intent":"investigate-incident","params":{"system":"api"},"confidence":0.91}'::jsonb, 'train', 0.910, true),
(3, 'something is broken in prod', '{"role":"sre"}'::jsonb,
 '{"intent":"investigate-incident","params":{"env":"prod"},"confidence":0.95}'::jsonb, 'train', 0.950, true),
(3, 'check error rates', '{"role":"sre"}'::jsonb,
 '{"intent":"investigate-incident","params":{"metric":"error_rate"},"confidence":0.78}'::jsonb, 'test', 0.780, true),
(4, 'review prs', '{"role":"developer"}'::jsonb,
 '{"intent":"review-pull-request","params":{},"confidence":0.96}'::jsonb, 'train', 0.960, true),
(4, 'whats waiting on me to approve', '{"role":"developer"}'::jsonb,
 '{"intent":"review-pull-request","params":{"assigned":true},"confidence":0.84}'::jsonb, 'dev', 0.840, true),
(5, 'plan next sprint', '{"role":"manager"}'::jsonb,
 '{"intent":"plan-sprint","params":{"horizon":"next"},"confidence":0.95}'::jsonb, 'train', 0.950, true),
(6, 'how are we doing this quarter', '{"role":"executive"}'::jsonb,
 '{"intent":"check-kpis","params":{"period":"quarter"},"confidence":0.92}'::jsonb, 'train', 0.920, true),
(6, 'show me the numbers', '{"role":"executive"}'::jsonb,
 '{"intent":"check-kpis","params":{},"confidence":0.81}'::jsonb, 'dev', 0.810, true),
(7, 'build me a sales dashboard', '{"role":"executive"}'::jsonb,
 '{"intent":"build-dashboard","params":{"topic":"sales"},"confidence":0.94}'::jsonb, 'train', 0.940, true),
(7, 'assemble a dashboard for our latency SLOs', '{"role":"sre"}'::jsonb,
 '{"intent":"build-dashboard","params":{"topic":"slo"},"confidence":0.89}'::jsonb, 'train', 0.890, true),
(8, 'find a time to meet with rosa', '{}'::jsonb,
 '{"intent":"schedule-meeting","params":{"attendee":"rosa"},"confidence":0.93}'::jsonb, 'train', 0.930, true),
(9, 'why is this query slow', '{"role":"developer"}'::jsonb,
 '{"intent":"debug-slow-query","params":{},"confidence":0.91}'::jsonb, 'train', 0.910, true),
(10, 'approve the AWS invoice', '{"role":"manager"}'::jsonb,
 '{"intent":"approve-expense","params":{"vendor":"aws"},"confidence":0.93}'::jsonb, 'train', 0.930, true),
(11, 'remind me about this tomorrow', '{}'::jsonb,
 '{"intent":"triage-inbox-snooze","params":{"when":"tomorrow"},"confidence":0.92}'::jsonb, 'train', 0.920, true),
(12, 'write me a long product spec', '{"role":"pm"}'::jsonb,
 '{"intent":"compose-doc","params":{"type":"product-spec"},"confidence":0.93}'::jsonb, 'train', 0.930, true),
(12, 'draft a press release', '{"role":"executive"}'::jsonb,
 '{"intent":"compose-doc","params":{"type":"press-release"},"confidence":0.88}'::jsonb, 'dev', 0.880, true),
(6, 'pull up the revenue chart', '{"role":"executive"}'::jsonb,
 '{"intent":"check-kpis","params":{"metric":"revenue"},"confidence":0.84}'::jsonb, 'test', 0.840, true),
(3, 'graphs look weird in payments', '{"role":"developer"}'::jsonb,
 '{"intent":"investigate-incident","params":{"system":"payments"},"confidence":0.79}'::jsonb, 'test', 0.790, true),
(4, 'who needs my review', '{"role":"developer"}'::jsonb,
 '{"intent":"review-pull-request","params":{"assigned":true},"confidence":0.86}'::jsonb, 'test', 0.860, true)
ON CONFLICT DO NOTHING;
